# Generated by Django 5.2.5 on 2025-08-28 20:33

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "poste_actuel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "entreprise_actuelle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Candidat",
                "verbose_name_plural": "Candidats",
            },
            bases=("api.customuser",),
            managers=[
                ("objects", api.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Recruteur",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nom_entreprise", models.CharField(max_length=255)),
                ("siret", models.CharField(max_length=14, unique=True)),
                ("nom_gerant", models.CharField(blank=True, max_length=255, null=True)),
                ("email_professionnel", models.EmailField(max_length=254, unique=True)),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logo", models.URLField(blank=True, null=True)),
                ("site_web", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Recruteur",
                "verbose_name_plural": "Recruteurs",
            },
            bases=("api.customuser",),
            managers=[
                ("objects", api.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", api.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
