# Generated by Django 5.2.5 on 2025-08-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_candidat_recruteur_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidat",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="recruteur",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
