# Generated by Django 5.2.5 on 2025-08-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_candidat_options_alter_recruteur_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "exigences",
                    models.TextField(
                        help_text="Compétences et qualifications requises"
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("Stage", "Stage"),
                            ("Freelance", "Freelance"),
                            ("Alternance", "Alternance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "salaire_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salaire minimum en euros",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "salaire_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salaire maximum en euros",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("localisation", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "date_expiration",
                    models.DateTimeField(help_text="Date limite pour postuler"),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "recruteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="api.recruteur",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        help_text="Fichier CV (PDF)", upload_to="candidatures/cv/"
                    ),
                ),
                (
                    "lettre_motivation",
                    models.FileField(
                        blank=True,
                        help_text="Lettre de motivation (PDF)",
                        null=True,
                        upload_to="candidatures/lettres/",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En Attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_candidature", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="api.candidat",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="api.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_candidature"],
                "unique_together": {("candidat", "job")},
            },
        ),
    ]
