# Generated by Django 5.2.5 on 2025-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de profil du candidat', null=True, upload_to='candidats/photos/'),
        ),
    ]
