# Generated by Django 5.2.5 on 2025-08-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_photo_to_candidat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='photo',
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='recruteurs/logos/'),
        ),
    ]
