# Generated by Django 5.2.5 on 2025-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_candidat_photo_alter_recruteur_logo'),
    ]

    operations = [
        # Mettre à jour les enregistrements existants avec des valeurs par défaut
        migrations.RunSQL(
            "UPDATE api_recruteur SET nom_gerant = 'Non renseigné' WHERE nom_gerant IS NULL OR nom_gerant = '';",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "UPDATE api_recruteur SET localisation = 'Non renseignée' WHERE localisation IS NULL OR localisation = '';",
            reverse_sql="SELECT 1;"
        ),
        # Modifier les champs pour les rendre obligatoires
        migrations.AlterField(
            model_name='recruteur',
            name='nom_gerant',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='localisation',
            field=models.CharField(max_length=255),
        ),
    ]
