# Generated by Django 5.0.7 on 2025-08-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_auto_20250829_1055"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score global de pertinence (0-1)",
                        null=True,
                    ),
                ),
                (
                    "skill_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de pertinence des compétences (0-1)",
                        null=True,
                    ),
                ),
                (
                    "experience_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de pertinence de l'expérience (0-1)",
                        null=True,
                    ),
                ),
                (
                    "education_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de pertinence de la formation (0-1)",
                        null=True,
                    ),
                ),
                (
                    "skills_extracted",
                    models.JSONField(
                        default=list, help_text="Liste des compétences extraites du CV"
                    ),
                ),
                (
                    "experience_extracted",
                    models.JSONField(
                        default=list, help_text="Informations d'expérience extraites"
                    ),
                ),
                (
                    "education_extracted",
                    models.JSONField(
                        default=list, help_text="Informations de formation extraites"
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Temps de traitement en secondes",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Message d'erreur si l'analyse a échoué"
                    ),
                ),
                (
                    "candidature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="api.candidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse IA de CV",
                "verbose_name_plural": "Analyses IA de CV",
                "ordering": ["-analysis_date"],
            },
        ),
    ]
