# Generated by Django 5.2.5 on 2025-08-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cvanalysis'),
        ('api', '0008_job_experience_job_keywords'),
    ]

    operations = [
    ]
