# Generated by Django 5.2.5 on 2025-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250829_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvanalysis',
            name='education_extracted',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='experience_extracted',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='skills_extracted',
        ),
        migrations.RemoveField(
            model_name='cvanalysis',
            name='status',
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='education',
            field=models.TextField(default='[]', help_text='Informations de formation extraites (format JSON string)'),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='experience',
            field=models.TextField(default='[]', help_text="Informations d'expérience extraites (format JSON string)"),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='raw_analysis',
            field=models.TextField(blank=True, default='', help_text="Analyse brute de l'IA"),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='skills',
            field=models.TextField(default='[]', help_text='Liste des compétences extraites du CV (format JSON string)'),
        ),
    ]
